import { IMAGES } from '@/Constants/constants';

export const topics = [
    {
        id: 't001',
        name: 'Array',
        icon: IMAGES.dsa.array,
        totalQuestions: 1915,
        saved: 8478,
        solved: 13,
        easy: { solved: 7, total: 394 },
        medium: { solved: 6, total: 1032 },
        hard: { solved: 0, total: 489 },
        lastUpdated: '6 days ago',
    },
    {
        id: 't002',
        name: 'String',
        icon: IMAGES.dsa.string,
        totalQuestions: 1024,
        saved: 5823,
        solved: 60,
        easy: { solved: 20, total: 300 },
        medium: { solved: 30, total: 500 },
        hard: { solved: 10, total: 224 },
        lastUpdated: '2 days ago',
    },
    {
        id: 't003',
        name: 'Dynamic Programming',
        icon: IMAGES.dsa.dp,
        totalQuestions: 876,
        saved: 7021,
        solved: 110,
        easy: { solved: 15, total: 120 },
        medium: { solved: 65, total: 500 },
        hard: { solved: 30, total: 256 },
        lastUpdated: '1 day ago',
    },
    {
        id: 't004',
        name: 'Graph',
        icon: IMAGES.dsa.graph,
        totalQuestions: 540,
        saved: 4150,
        solved: 45,
        easy: { solved: 10, total: 100 },
        medium: { solved: 25, total: 300 },
        hard: { solved: 10, total: 140 },
        lastUpdated: '4 days ago',
    },
    {
        id: 't005',
        name: 'Binary Tree',
        icon: IMAGES.dsa.tree,
        totalQuestions: 690,
        saved: 5285,
        solved: 80,
        easy: { solved: 20, total: 200 },
        medium: { solved: 40, total: 350 },
        hard: { solved: 20, total: 140 },
        lastUpdated: '3 days ago',
    },
];
